# Generated by Django 2.0.3 on 2019-11-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regular_pizza',
            name='items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sicilian_pizza',
            name='items',
            field=models.IntegerField(default=0),
        ),
    ]
