# Generated by Django 2.0.3 on 2019-11-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191118_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='size',
            field=models.CharField(max_length=40),
        ),
    ]
